<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="1" hostname="eduardo-Aspire-E5-473" id="0" name="UserIntegrationSpec" package="com.grailsinaction" tests="4" time="0.68" timestamp="2016-02-12T16:28:08">
      <properties />

      <testcase classname="com.grailsinaction.UserIntegrationSpec" name="Saving our first user to the database" time="0.55" />

      <testcase classname="com.grailsinaction.UserIntegrationSpec" name="Updating a saved user changes its properties" time="0.012" />

      <testcase classname="com.grailsinaction.UserIntegrationSpec" name="Deleting an existing user removes it from the database" time="0.062" />

      <testcase classname="com.grailsinaction.UserIntegrationSpec" name="Saving a user with invalid properties causes an error" time="0.054">
          <failure message="Condition not satisfied:&#xa;&#xa;user.hasErrors()&#xa;|    |&#xa;|    false&#xa;com.grailsinaction.User : 4&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Condition not satisfied:

user.hasErrors()
|    |
|    false
com.grailsinaction.User : 4

	at com.grailsinaction.UserIntegrationSpec.Saving a user with invalid properties causes an error(UserIntegrationSpec.groovy:79)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from Saving our first user to the database--
--Output from Updating a saved user changes its properties--
--Output from Deleting an existing user removes it from the database--
--Output from Saving a user with invalid properties causes an error--
]]></system-out>

      <system-err><![CDATA[--Output from Saving our first user to the database--
--Output from Updating a saved user changes its properties--
--Output from Deleting an existing user removes it from the database--
--Output from Saving a user with invalid properties causes an error--
]]></system-err>

  </testsuite>
</testsuites>
